# Site settings
title: RUDOS Coffee truck
email: caferudos@gmail.com
url: https://www.rudos.fr
description: "Café Meylan"
keywords: "Café, coffeetruck, foodtruck, coffee shop, specialty coffee"
hello_msg: "Café, thé et gourmandises"
quote: " \"Si le café est bon, tout est bon.\""
quoteAuth: "FRANCIS BEATTY THURBER"
meta_author: HASLAM Malcolm
contact_msg: "Vous voulez privatiser Rudos (petit-déjeuners d'entreprise, brunchs, évènements privés ou professionnels, etc.) ? </br>Vous avez une question, une suggestion ou une plainte? Ou vous voulez simplement me contacter?</br></br>Envoyez-moi un message ou whats app! "
findus_M_date: "7h00-12h00"
findus_M_palce: "<a class='text-link' href='https://goo.gl/maps/UudeXbsZgQSXyx147'>(Gare de Brignoud, Villard-Bonnot)</a>"
findus_T_date: "7h00-12h00"
findus_T_palce: "<a class='text-link' href='https://goo.gl/maps/LGyp9A68TA8kDYBt9'>(Place de la Louisiane, Meylan)</a>" 
findus_W_date: "7h00-12h00"
findus_W_palce:  "<a class='text-link' href='https://goo.gl/maps/UudeXbsZgQSXyx147'>(Gare de Brignoud, Villard-Bonnot)</a>"
findus_TH_date: "7h00-12h00"
findus_TH_palce:   "<a class='text-link' href='https://goo.gl/maps/UudeXbsZgQSXyx147'>(Gare de Brignoud, Villard-Bonnot)</a>"
findus_F_date: "7h00-12h00"
findus_F_palce:   "<a class='text-link' href='https://goo.gl/maps/UudeXbsZgQSXyx147'>(Gare de Brignoud, Villard-Bonnot)</a>"
findus_S_date: "FERMÉ"
findus_S_palce: ""
findus_SU_date: "FERMÉ"
findus_SU_palce: ""
about_left: <img src="/img/camion.jpg" alt="">
about_right: "
              &emsp;&emsp;&emsp;Après des années au service de l'ingénierie informatique, Malcolm a décidé de se lancer dans ce qui était une passion jusqu'à là : le café! 
              Il suit alors une formation professionnalisante de barista pour affiner ses compétences et le voilà au volant de sa caravane bleue, sous le nom de 
              <span class='p-text-name'>Rudos</span>. Ceci dit, il reste un détail à régler : le choix des produits et des fournisseurs!
              <br> 
Cela fut une évidence que le café utilisé devrait être respectueux des hommes, de l'environnement et s'il put être Bio encore mieux! 
Il n'y a donc plus qu'à trouver des torréfacteurs locaux labélisés partageant le même engagement. Chose faite : <span class='p-text-name'>Rudos</span> 
travaillera principalement avec le <a class='text-link' href='https://cafechulo.fr' target='_blank' rel='noopener noreferrer'>Café Chulo</a> (Fontaine) et 
<a class='text-link' href='https://cafemoxka.com' target='_blank' rel='noopener noreferrer'>Moxka</a> (Lyon).<br> 
On ajoute à cela, une recherche minutieuse de la meilleure recette des cookies et cakes, et le camion est ouvert!<br>
<br>
&emsp;&emsp;&emsp;<span class='p-text-name'>Rudos</span> est alors un camion ambulant qui propose du café de spécialité, des boissons chaudes et froides, ainsi que des gourmandises associées, le tout de provenances au maximum locales et traçables.
            "

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: Malcolm

# Color settings (hex-codes without the leading hash-tag)4ab19a
color:
  primary: e0ebe8 #18bc9c #80B3FF
  primary-rgb: "128,179,255" #"24,288,156"
  secondary: 4ab19a #2c3e50 #FD6E8A
  secondary-dark: dc612c #233140 #A2122F
  text: 194e6d
  off-white: fdfdfc

# Footer settings
footer:
  copyright: MH Speciality Coffee
  location: Siège 
  social: Autour du Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/CafeRudos
  - title: instagram
    url: https://www.instagram.com/caferudos/
  - title: whatsapp
    url:  https://wa.me/0668115398


# Postal address (add as many lines as necessary)
address:
  - line: Crolles, France 
  - line: <i class="fa fa-fw fa-phone" aria-hidden="true"></i>+33 06 68 11 53 98

# Credits content
credits: 'Merci à tous les clients et prestataires qui assistent Rudos dans sa recherche de la tasse idéale'

# Build settings
markdown: kramdown
permalink: pretty
