# Site settings
title: RUDOS
email: caferudos@gmail.com
url: https://example.github.io
description: "Café d'exeption Meylan"
keywords: "Café"
hello_msg: "Café, thé et gourmandises"
quote: " \"Si le café est bon, tout est bon.\""
quoteAuth: "FRANCIS BEATTY THURBER"
meta_author: HASLAM Malcolm
contact_msg: "Vous avez des questions sur quoi que ce soit..."
about_left: <img src="/img/cap.jpg" alt="">
about_right: "
              Rudos est un camion ambulant, au sein de la vallée du Grésivaudan, qui propose du café d’exception, des boissons chaudes et froides, ainsi que des gourmandises associées, de provenances au maximum locales et traçables.

            "

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: Malcolm

# Color settings (hex-codes without the leading hash-tag)4ab19a
color:
  primary: e0ebe8 #18bc9c #80B3FF
  primary-rgb: "128,179,255" #"24,288,156"
  secondary: 4ab19a #2c3e50 #FD6E8A
  secondary-dark: dc612c #233140 #A2122F
  text: 194e6d
  off-white: fdfdfc

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/malcolm-haslam-4017a82a/
  - title: github
    url: https://github.com/mhaslam
  - title: twitter
    url: https://twitter.com/MalcolmHaslam


# Postal address (add as many lines as necessary)
address:
  - line: Crolles, France

# Credits content
credits: 'Thank you for all the inpiration (and openSource code) I used on this page. It is now a clean site with a simple minimalistic UX.  
I till have a lot of ideas to implement so keep refreshing! 
<br />
Traduction française à venir.
'

# Build settings
markdown: kramdown
permalink: pretty
